#!/bin/bash

# Configure python pip cache directory
export XDG_CACHE_HOME=/tmp/

# Activate python environment
source /usr/lib/ckan/env/bin/activate

# Install and update pip and pip tools
pip install -U pip --no-index -f /usr/lib/ckanext-searchindexhook/requirements
pip install -U setuptools --no-index -f /usr/lib/ckanext-searchindexhook/requirements
pip install -U wheel --no-index -f /usr/lib/ckanext-searchindexhook/requirements

# Install ckanext-searchindexhook and it's requirements
pip install --no-index -f /usr/lib/ckanext-searchindexhook/requirements ckanext-searchindexhook

# Add ckan plugin "search_index_hook" to production.ini
if ! grep "ckan.plugins.*search_index_hook" /etc/ckan/default/production.ini
then
  sed -i '/^ckan.plugins/ s/$/ search_index_hook/' /etc/ckan/default/production.ini
fi
